### ISSUE TITLE
'delete m_symbolList'  in TraceError.h  should be 'free( m_symbolList ); '

### ISSUE THREAD

**Issue by yzznw** [EricZinda/InductorHtn#4]
First, thanks this project. I really like it.

in TraceError.h, there is code below:
~~~
 ~TraceError()
    {
             delete m_symbolList; 
            m_symbolList = nullptr;
    }
~~~
in TraceError_Pos.cpp,  m_symbolList is returned by backtrace_symbols().  The 'backtrace_symbols()' document said:
       ... The address of the array of
       string pointers is returned as the function result of
       backtrace_symbols().  This array is [malloc(3)](http://man7.org/linux/man-pages/man3/malloc.3.html)ed by
       backtrace_symbols(), and must be freed by the caller.  (The strings
       pointed to by the array of pointers need not and should not be
       freed.)
see: https://www.man7.org/linux/man-pages/man3/backtrace.3.html

so, it should be:   std::free( m_symbolList );

in other platform ( Android, Window ),  consider pre-alloc memory manually :  m_symbolList = std::alloc ( ... ).

**Comment by EricZinda** [comment]
Thanks for reporting!  Let me take a look ...

**Comment by EricZinda** [comment]
OK, Fixed! In both InductorHtn and InductorProlog.  thanks again for reporting!
